{% set name = "dvc-data" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb5026754f7b6d6a0051e49975c9116571933d3349a6db49f211f1237882b830

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - dictdiffer >=0.8.1
    - pygtrie >=2.3.2
    - shortuuid >=0.5.0
    - dvc-objects <1,>=0.24.1
    - nanotime >=0.5.2
    - diskcache >=5.2.1
    - attrs >=21.3.0
    - sqltrie <1,>=0.6.0

test:
  imports:
    - dvc_data
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - daavoo
    - pmrowla
    - shcheklein
    - skshetry
