{% set name = "dvc-data" %}
{% set version = "3.16.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54e8992a907ce4d0dca2dbd6b470e7b7c77f6f86613a9009b58c503154f4c6a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.3.1
  run:
    - orjson >=3,<4
    - python >={{ python_min }}
    - attrs >=21.3.0
    - dictdiffer >=0.8.1
    - diskcache >=5.2.1
    - dvc-objects >=4.0.1,<6
    - fsspec >=2024.2.0
    - funcy >=1.14
    - pygtrie >=2.3.2
    - sqltrie >=0.11.0,<1
    - tqdm >=4.63.1,<5

test:
  imports:
    - dvc_data
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-data
  summary: DVC data management library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - daavoo
    - pmrowla
    - shcheklein
    - skshetry
